max_width = 90
binop_separator = "Front"
combine_control_expr = false
comment_width = 100
hard_tabs = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
imports_granularity = "Item"
match_block_trailing_comma = true
merge_derives = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
# struct_field_align_threshold = 100
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
format_code_in_doc_comments = true
